=== CaishunChen/K-OS--Driver-Kit/drivers/ddfs/ddf.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--W3C Schema generated by XMLSpy v2009 sp1 (http://www.altova.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="module-list">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="module" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="module">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="id" use="required">
						<xs:simpleType>
							<xs:restriction base="xs:string">
								<xs:enumeration value="ATD"/>
								<xs:enumeration value="BDLC"/>
								<xs:enumeration value="ECT"/>
								<xs:enumeration value="EEPROM"/>
								<xs:enumeration value="FLASH"/>
								<xs:enumeration value="PWM"/>
								<xs:enumeration value="SCI"/>
								<xs:enumeration value="SPI"/>
								<xs:enumeration value="TIM"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
					<xs:attribute name="description" use="required">
						<xs:simpleType>
							<xs:restriction base="xs:string">
								<xs:enumeration value="32-KByte Flash-EEPROM"/>
								<xs:enumeration value="768-Byte EEPROM"/>
								<xs:enumeration value="8-channel, 10-bit, analog-to-digital converter"/>
								<xs:enumeration value="Asynchronous serial communications interface"/>
								<xs:enumeration value="Enhanced capture timer"/>
								<xs:enumeration value="Pulse-width modulator"/>
								<xs:enumeration value="Standard timer module"/>
								<xs:enumeration value="Synchronous serial peripheral interface"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="device-description">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="module-list"/>
			</xs:sequence>
			<xs:attribute name="id" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="MC68HC912B32"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== CaishunChen/K-OS--Driver-Kit/drivers/ddfs/hc12/MC68HC912B32.xml
<device-description id="MC68HC912B32" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C:\projekte\csProjects\common\drivers\ddfs\ddf.xsd">
	<module-list>
		<module id="FLASH" description="32-KByte Flash-EEPROM">
		</module>
		<module id="EEPROM" description="768-Byte EEPROM">
		</module>
		<module id="ATD" description="8-channel, 10-bit, analog-to-digital converter">
		</module>
		<module id="TIM" description="Standard timer module">
		</module>
		<module id="ECT" description="Enhanced capture timer">
		</module>
		<module id="PWM" description="Pulse-width modulator">
		</module>
		<module id="SCI" description="Asynchronous serial communications interface">
		</module>
		<module id="SPI" description="Synchronous serial peripheral interface">
		</module>
		<module id="BDLC" description="Synchronous serial peripheral interface">
		</module>
	</module-list>
</device-description>
